apiVersion: apps/v1
kind: Deployment
metadata:
  name: patvin-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: patvin
      component: api
  template:
    metadata:
      labels:
        app: patvin
        component: api
    spec:
      imagePullSecrets:
      - name: patvin-registry
      containers:
      - name: patvin-api
        image: image
        env:
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: patvin-api-secrets
              key: POSTGRES_HOST
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: patvin-api-secrets
              key: POSTGRES_PORT
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: patvin-api-secrets
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: patvin-api-secrets
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DATABASE
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: POSTGRES_DATABASE
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: PGADMIN_DEFAULT_EMAIL
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: PGADMIN_DEFAULT_PASSWORD
        - name: AUTH_SALT_ROUNDS
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: AUTH_SALT_ROUNDS
        - name: AUTH_SECRET
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: AUTH_SECRET
        - name: AUTH_REFRESH_SECRET
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: AUTH_REFRESH_SECRET
        - name: AUTH_TOKEN_LIFETIME
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: AUTH_TOKEN_LIFETIME
        - name: AUTH_REFRESH_TOKEN_LIFETIME
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: AUTH_REFRESH_TOKEN_LIFETIME
        - name: NODE_TLS_REJECT_UNAUTHORIZED
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: NODE_TLS_REJECT_UNAUTHORIZED
        - name: WEB_LINK
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: WEB_LINK
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: AWS_ACCESS_KEY_ID
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: AWS_SECRET_ACCESS_KEY
        - name: BUCKET_NAMES
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: BUCKET_NAMES
        - name: MAIL_HOST
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: MAIL_HOST
        - name: MAIL_USER
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: MAIL_USER
        - name: MAIL_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: MAIL_PASSWORD
        - name: MAIL_FROM
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: MAIL_FROM
        - name: MAIL_TRANSPORT
          valueFrom:
            configMapKeyRef:
              name: patvin-api-config-map
              key: MAIL_TRANSPORT
        ports:
        - containerPort: 3000